name: Pings
on:
    workflow_dispatch:
jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: ping
              run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{github.token}}"" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Spudd1e/pong/dispatches \
                -d '{"event_type":"ping!","client_payload":{"message" : "ping!"}'
        